import { SectionHeading } from "@/components/shared/SectionHeading"
import { CtaButton } from "@/components/shared/CtaButton"
import { ASSESSMENT_URL } from "@/lib/constants"

const STEPS = [
  {
    number: "1",
    title: "Get Your Plan",
    description:
      "Answer 4 quick questions about your business and get a free personalised automation plan — your top opportunities, time savings estimates, and what to tackle first. Generated by Claude AI, emailed to you instantly.",
  },
  {
    number: "2",
    title: "Book Your Audit",
    description:
      "If the plan resonates, book a free 30-minute call. I'll have already reviewed your answers — so we skip the basics and go straight to how to get it done. Fixed price, clear scope, no surprises.",
  },
  {
    number: "3",
    title: "Build & Run",
    description:
      "I design and build your automations using tools your team already knows. Everything is documented and handed over. Optional ongoing support if you want it.",
  },
]

export function HowItWorks() {
  return (
    <section className="bg-white py-16 sm:py-20">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <SectionHeading>Three Steps. No Complexity.</SectionHeading>

        <div className="mx-auto max-w-3xl">
          <div className="space-y-8">
            {STEPS.map((step) => (
              <div key={step.number} className="flex gap-5">
                <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary text-white font-heading font-bold">
                  {step.number}
                </div>
                <div>
                  <h3 className="font-heading text-xl font-semibold text-text-primary">
                    {step.title}
                  </h3>
                  <p className="mt-2 text-text-secondary">{step.description}</p>
                </div>
              </div>
            ))}
          </div>

          <div className="mt-10 text-center">
            <CtaButton href={ASSESSMENT_URL} size="lg" ctaLocation="how-it-works">
              Get Your Free Automation Plan
            </CtaButton>
            <p className="mt-2 text-sm text-text-muted">Takes 4 minutes · Free · No obligation</p>
          </div>
        </div>
      </div>
    </section>
  )
}
